services:
  - type: web
    name: flowee-band-vote
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeployTrigger: commit
    envVars:
      - key: BANDVOTE_DB_PATH
        value: /opt/render/project/src/data/bandvote.db
