services:
  - type: web
    name: flowee-band-vote
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeployTrigger: commit
    envVars:
      - key: DATABASE_URL
        sync: false
