spring.application.name=band-vote-app
server.address=0.0.0.0
server.port=${PORT:8080}
spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
spring.jackson.time-zone=Asia/Seoul

bandvote.db.path=${BANDVOTE_DB_PATH:data/bandvote.db}
